#!/usr/bin/env bash
# Generate deploy/.env with unique secrets for the RAW compose target (SPEC-18, FR-18.x).
# Idempotent: if deploy/.env already exists it is left untouched (secrets are never rotated here).
# Coolify/Dokploy do NOT need this — their platforms inject secrets (see README).
set -euo pipefail

ENV_FILE="$(dirname "$0")/.env"
if [[ -f "$ENV_FILE" ]]; then
  echo "deploy/.env already exists — leaving it untouched." >&2
  exit 0
fi

gen() { openssl rand -base64 24 | tr -d '/+=' | cut -c1-32; }

POSTGRES_PASSWORD="$(gen)"
ADMIN_PASSWORD="$(gen)"

cat > "$ENV_FILE" <<EOF
# Autogenerated by deploy/init-secrets.sh — unique to this install. DO NOT commit.
POSTGRES_USER=rsc_brain
POSTGRES_DB=rsc_brain
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Public domain for automatic HTTPS (Caddy). Set to your real domain before going live.
RSC_BRAIN_DOMAIN=localhost

# First admin — created on first \`brain init\`. Change the email; the value stays in this file.
RSC_BRAIN_ADMIN_EMAIL=admin@rsc-brain.local
RSC_BRAIN_ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Model routes belong in the private api/worker Compose override described in deploy/README.md.
EOF
chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE with unique secrets (mode 600)." >&2
