"""agents and service PATs

Revision ID: 1f461b206f32
Revises: 9556a451b272
Create Date: 2026-07-24 04:45:53.319200
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1f461b206f32'
down_revision: str | None = '9556a451b272'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_topics', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_agents_owner_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_agents_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index('ix_agents_project_id_id', 'agents', ['project_id', 'id'], unique=False)
    op.add_column('personal_access_tokens', sa.Column('agent_id', sa.Uuid(), nullable=True))
    op.alter_column('personal_access_tokens', 'membership_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_personal_access_tokens_agent_id_agents'), 'personal_access_tokens', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    # Exactly one principal per token: a human membership XOR a service agent.
    op.create_check_constraint(
        op.f("ck_personal_access_tokens_exactly_one_principal"),
        "personal_access_tokens",
        "(membership_id IS NOT NULL) <> (agent_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_personal_access_tokens_exactly_one_principal"), 'personal_access_tokens', type_='check')
    op.drop_constraint(op.f('fk_personal_access_tokens_agent_id_agents'), 'personal_access_tokens', type_='foreignkey')
    op.alter_column('personal_access_tokens', 'membership_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('personal_access_tokens', 'agent_id')
    op.drop_index('ix_agents_project_id_id', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
