"""initial schema PRD 5.2

Revision ID: 9556a451b272
Revises: 
Create Date: 2026-07-24 03:54:42.656732
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

revision: str = '9556a451b272'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Extensions must exist before any table with a Vector column is created. AGE requires
    # shared_preload_libraries=age (set by the data image); vanilla Postgres cannot run this.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS age")
    op.create_table('oauth_clients',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('client_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_clients')),
    sa.UniqueConstraint('client_id', name=op.f('uq_oauth_clients_client_id'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('slug', name=op.f('uq_projects_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('principal_type', sa.Text(), nullable=True),
    sa.Column('principal_id', sa.Text(), nullable=True),
    sa.Column('on_behalf_of', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=True),
    sa.Column('query_hash', sa.Text(), nullable=True),
    sa.Column('topics_used', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('denied', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audit_log_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_project_id_ts', 'audit_log', ['project_id', 'ts'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_entities_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('project_id', 'normalized_name', 'type', name=op.f('uq_entities_project_id_normalized_name_type'))
    )
    op.create_index('ix_entities_project_id_id', 'entities', ['project_id', 'id'], unique=False)
    op.create_table('gaps',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('query_hash', sa.Text(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_gaps_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gaps'))
    )
    op.create_index('ix_gaps_project_id_query_hash', 'gaps', ['project_id', 'query_hash'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_invitations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations'))
    )
    op.create_table('persons',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('topics', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_persons_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_persons_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index('ix_persons_project_id_id', 'persons', ['project_id', 'id'], unique=False)
    op.create_table('project_memberships',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('allowed_topics', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('can_curate', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_memberships_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_memberships')),
    sa.UniqueConstraint('user_id', 'project_id', name=op.f('uq_project_memberships_user_id_project_id'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('default_tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('policy', sa.Text(), nullable=False),
    sa.Column('review_if_sensitive', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('curators', postgresql.ARRAY(sa.Uuid()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index('ix_sources_project_id_id', 'sources', ['project_id', 'id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sensitivity', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_topics_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('project_id', 'slug', name=op.f('uq_topics_project_id_slug'))
    )
    op.create_index('ix_topics_project_id_id', 'topics', ['project_id', 'id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('logical_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('lang', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('doc_tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_documents_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_documents_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('project_id', 'checksum', name=op.f('uq_documents_project_id_checksum'))
    )
    op.create_index('ix_documents_project_id_id', 'documents', ['project_id', 'id'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('approved', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_aliases_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_entity_aliases_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_aliases'))
    )
    op.create_index('ix_entity_aliases_project_id_entity_id', 'entity_aliases', ['project_id', 'entity_id'], unique=False)
    op.create_table('hunts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('gap_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gap_id'], ['gaps.id'], name=op.f('fk_hunts_gap_id_gaps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_hunts_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_hunts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hunts'))
    )
    op.create_index('ix_hunts_project_id_state', 'hunts', ['project_id', 'state'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('access_token_hash', sa.Text(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], name=op.f('fk_oauth_tokens_client_id_oauth_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['project_memberships.id'], name=op.f('fk_oauth_tokens_membership_id_project_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_tokens'))
    )
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['project_memberships.id'], name=op.f('fk_personal_access_tokens_membership_id_project_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_access_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_personal_access_tokens_token_hash'))
    )
    op.create_table('skills',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('when_to_use', sa.Text(), nullable=True),
    sa.Column('when_not', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('owner_person_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['owner_person_id'], ['persons.id'], name=op.f('fk_skills_owner_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_skills_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('project_id', 'slug', name=op.f('uq_skills_project_id_slug'))
    )
    op.create_index('ix_skills_project_id_id', 'skills', ['project_id', 'id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_chunks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index('ix_chunks_project_id_document_id', 'chunks', ['project_id', 'document_id'], unique=False)
    op.create_table('ingest_errors',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_ref', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ingest_errors_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ingest_errors_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_errors'))
    )
    op.create_index('ix_ingest_errors_project_id_document_id', 'ingest_errors', ['project_id', 'document_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('predicate', sa.Text(), nullable=True),
    sa.Column('object', sa.Text(), nullable=True),
    sa.Column('credibility', sa.Numeric(), server_default='0.5', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('importance', sa.Numeric(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_claims_chunk_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_claims_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index('ix_claims_project_id_chunk_id', 'claims', ['project_id', 'chunk_id'], unique=False)
    # HNSW cosine indexes for chunk/claim embeddings (plan §resolved decisions).
    op.create_index(
        "ix_chunks_embedding_hnsw", "chunks", ["embedding"],
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_claims_embedding_hnsw", "claims", ["embedding"],
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_claims_embedding_hnsw", table_name="claims")
    op.drop_index("ix_chunks_embedding_hnsw", table_name="chunks")
    op.drop_index('ix_claims_project_id_chunk_id', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_ingest_errors_project_id_document_id', table_name='ingest_errors')
    op.drop_table('ingest_errors')
    op.drop_index('ix_chunks_project_id_document_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_skills_project_id_id', table_name='skills')
    op.drop_table('skills')
    op.drop_table('personal_access_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index('ix_hunts_project_id_state', table_name='hunts')
    op.drop_table('hunts')
    op.drop_index('ix_entity_aliases_project_id_entity_id', table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index('ix_documents_project_id_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_topics_project_id_id', table_name='topics')
    op.drop_table('topics')
    op.drop_index('ix_sources_project_id_id', table_name='sources')
    op.drop_table('sources')
    op.drop_table('project_memberships')
    op.drop_index('ix_persons_project_id_id', table_name='persons')
    op.drop_table('persons')
    op.drop_table('invitations')
    op.drop_index('ix_gaps_project_id_query_hash', table_name='gaps')
    op.drop_table('gaps')
    op.drop_index('ix_entities_project_id_id', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_audit_log_project_id_ts', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('oauth_clients')
    # ### end Alembic commands ###
