"""REST admin API (FR-10.2) — parity with the v0.1 CLI subset, admin-gated, OpenAPI-documented.

Every view need widens THIS API first (never direct DB): the console (SPEC-07) is built on the
autogenerated OpenAPI. Auth is a Bearer PAT resolved to a scope (SPEC-04) that must be an admin
(user role owner/admin, or a curator membership). Project-scoped endpoints take the project from
the token, never from client input (FR-12.3); the two global endpoints (list/create projects) are
plain admin operations.
"""

from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel, Field
from sqlalchemy import func, select

from rsc_brain import audit as audit_mod
from rsc_brain.identity.service import IdentityService
from rsc_brain.ingest.sources import SourceService
from rsc_brain.recall.gaps import list_gaps
from rsc_brain.scope import PrincipalType, ProjectScope
from rsc_brain.stores.relational import models
from rsc_brain.stores.relational.ingest_repository import IngestRepository

_bearer = HTTPBearer(auto_error=False)
_ADMIN_ROLES = {"owner", "admin"}

router = APIRouter(prefix="/api/v1/admin", tags=["admin"])


class ProjectCreate(BaseModel):
    slug: str
    name: str


class TopicCreate(BaseModel):
    slug: str
    name: str
    sensitivity: int = Field(default=0, ge=0)


class SourceCreate(BaseModel):
    name: str
    type: str = "folder"
    policy: str = "llm"
    default_tags: list[str] = Field(default_factory=list)
    review_if_sensitive: bool = True


class UserInvite(BaseModel):
    email: str
    role: str = "member"


def _deps(request: Request) -> object:
    return request.app.state.deps


async def _admin_scope(
    request: Request,
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer),
) -> ProjectScope:
    from rsc_brain.identity.resolve import resolve_scope

    deps = _deps(request)
    sessionmaker = deps.sessionmaker  # type: ignore[attr-defined]
    if credentials is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="missing bearer token")
    scope = await resolve_scope(sessionmaker, credentials.credentials)
    if scope is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="invalid token")
    if not await _is_admin(sessionmaker, scope):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="admin role required")
    return scope


async def _is_admin(sessionmaker: object, scope: ProjectScope) -> bool:
    if scope.can_curate:
        return True
    if scope.principal_type is not PrincipalType.HUMAN:
        return False
    async with sessionmaker() as session:  # type: ignore[operator]
        role = await session.scalar(
            select(models.User.role).where(models.User.id == uuid.UUID(scope.principal_id))
        )
    return role in _ADMIN_ROLES


def _identity(request: Request) -> IdentityService:
    return IdentityService(_deps(request).sessionmaker)  # type: ignore[attr-defined]


def _repo(request: Request) -> IngestRepository:
    return IngestRepository(_deps(request).sessionmaker)  # type: ignore[attr-defined]


# --- projects (global admin) ------------------------------------------------


@router.get("/projects")
async def list_projects(
    request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    return {"projects": await _identity(request).list_projects()}


@router.post("/projects", status_code=status.HTTP_201_CREATED)
async def create_project(
    body: ProjectCreate, request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    project_id = await _identity(request).create_project(body.slug, body.name)
    return {"project_id": project_id, "slug": body.slug}


# --- users (global admin) ---------------------------------------------------


@router.post("/users/invite", status_code=status.HTTP_201_CREATED)
async def invite_user(
    body: UserInvite, request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    issued = await _identity(request).invite_user(body.email, role=body.role)
    # The invitation token is shown once (the console surfaces it to the inviter).
    return {"user_id": issued.id, "invitation_token": issued.token}


# --- project-scoped (project from the token) --------------------------------


@router.get("/topics")
async def list_topics(
    request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    topics = await _repo(request).list_topics(scope)
    return {"topics": [{"slug": slug, "sensitivity": sens} for slug, sens in topics]}


@router.post("/topics", status_code=status.HTTP_201_CREATED)
async def create_topic(
    body: TopicCreate, request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    topic_id = await _identity(request).create_topic(
        scope.project_id, body.slug, body.name, sensitivity=body.sensitivity
    )
    return {"topic_id": topic_id, "slug": body.slug}


@router.get("/sources")
async def list_sources(
    request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    sources = await _repo(request).list_sources(scope)
    return {
        "sources": [
            {
                "id": s.id,
                "name": s.name,
                "type": s.type,
                "policy": s.policy,
                "default_tags": list(s.default_tags),
                "review_if_sensitive": s.review_if_sensitive,
            }
            for s in sources
        ]
    }


@router.post("/sources", status_code=status.HTTP_201_CREATED)
async def create_source(
    body: SourceCreate, request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    source_id = await SourceService(_repo(request)).create(
        scope,
        name=body.name,
        type_=body.type,
        policy=body.policy,
        default_tags=body.default_tags,
        review_if_sensitive=body.review_if_sensitive,
    )
    return {"source_id": source_id, "name": body.name}


@router.get("/documents/pending")
async def list_pending_documents(
    request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    pending = await _repo(request).list_documents_by_status(scope, "pending_approval")
    return {
        "documents": [
            {"document_id": d.id, "title": d.title, "proposed_tags": list(d.doc_tags)}
            for d in pending
        ]
    }


@router.get("/gaps")
async def list_project_gaps(
    request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    return {"gaps": await list_gaps(_deps(request).sessionmaker, scope)}  # type: ignore[attr-defined]


@router.get("/audit")
async def list_audit(
    request: Request, scope: ProjectScope = Depends(_admin_scope), limit: int = 100
) -> dict[str, object]:
    rows = await audit_mod.query_audit(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope.project_id,
        limit=limit,
    )
    return {"audit": rows}


@router.delete("/connections/{connection_id}")
async def admin_revoke_connection(
    connection_id: str, request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    """Admin revokes any user's OAuth connection (FR-4.13 admin part). Stops resolving <5s."""
    from rsc_brain.identity import sessions

    await sessions.revoke_connection(_deps(request).sessionmaker, connection_id)  # type: ignore[attr-defined]
    return {"ok": True, "revoked": connection_id}


# --- read observability (SPEC-14, all scoped to the token's project — FR-12.5) ---------------


class QueryTextLogging(BaseModel):
    enabled: bool


@router.get("/observability/activity")
async def observability_activity(
    request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    """Activity dashboard aggregates (FR-13.2): recalls/day, active principals, p95, denied."""
    return await audit_mod.activity_summary(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope.project_id,
    )


@router.get("/observability/recalls")
async def observability_recalls(
    request: Request,
    scope: ProjectScope = Depends(_admin_scope),
    principal_type: str | None = None,
    denied: bool | None = None,
    limit: int = 100,
) -> dict[str, object]:
    """Live recall stream (FR-13.3/14.3): filter by principal + denial; query_text present only
    when the project's logging is ON."""
    return {
        "recalls": await audit_mod.recall_stream(
            _deps(request).sessionmaker,  # type: ignore[attr-defined]
            scope.project_id,
            principal_type=principal_type,
            denied=denied,
            limit=limit,
        )
    }


@router.get("/observability/health")
async def observability_health(
    request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    """Service health (FR-13.2): the pending-approval queue depth + extraction error count."""
    sm = _deps(request).sessionmaker  # type: ignore[attr-defined]
    pid = uuid.UUID(scope.project_id)
    async with sm() as session:
        pending = await session.scalar(
            select(func.count())
            .select_from(models.Document)
            .where(models.Document.project_id == pid, models.Document.status == "pending_approval")
        )
        errors = await session.scalar(
            select(func.count())
            .select_from(models.IngestError)
            .where(models.IngestError.project_id == pid)
        )
    return {
        "database": "ok",
        "pending_approval": int(pending or 0),
        "ingest_errors": int(errors or 0),
    }


@router.get("/settings/query-text-logging")
async def get_query_text_logging(
    request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    enabled = await audit_mod.query_text_logging_enabled(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope.project_id,
    )
    return {"enabled": enabled}


@router.put("/settings/query-text-logging")
async def put_query_text_logging(
    body: QueryTextLogging, request: Request, scope: ProjectScope = Depends(_admin_scope)
) -> dict[str, object]:
    """Toggle FR-13.9 for the project. OFF ⇒ the query text stops being persisted (server-side)."""
    await audit_mod.set_query_text_logging(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope.project_id,
        enabled=body.enabled,
    )
    return {"enabled": body.enabled}
