"""REST admin API (FR-10.2) — parity with the v0.1 CLI subset, capability-gated, OpenAPI-documented.

Every view need widens THIS API first (never direct DB): the console (SPEC-07) is built on the
autogenerated OpenAPI. Two entry points resolve to the same authority: a Bearer PAT/OAuth token
(project from the token, FR-12.3) or a console session plus the ``?project=`` slug it is authorized
for. Neither is trusted beyond identity — every route then names the *operation* it performs and
:func:`rsc_brain.authorization.decide` answers it against the ratified role matrix (AUDIT-020).

What that replaced (R03/R04): a single ``_is_admin`` helper that accepted ``can_curate`` as
administration, so a curator reached the whole surface while the project administrator the matrix
actually designates was locked out of it.
"""

from __future__ import annotations

import uuid
from collections.abc import Callable, Coroutine
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query, Request, Response, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel, Field
from sqlalchemy import func, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from rsc_brain import audit as audit_mod
from rsc_brain.api.authz import (
    decide_document,
    decide_object,
    enforce,
    merge_proposal_topics,
    object_topics,
)
from rsc_brain.authorization import Allow, Capability, decide
from rsc_brain.config.models import PublicLimits
from rsc_brain.identity.service import IdentityService
from rsc_brain.ingest.sources import SourceService
from rsc_brain.mcp.tools import UNTRUSTED
from rsc_brain.recall.gaps import list_gaps
from rsc_brain.scope import (
    PROJECT_ROLE_ADMIN,
    PROJECT_ROLE_MEMBER,
    PROJECT_ROLE_VIEWER,
    Principal,
    PrincipalType,
    ProjectScope,
)
from rsc_brain.stores.relational import models
from rsc_brain.stores.relational.ingest_repository import IngestRepository
from rsc_brain.stores.relational.knowledge_store import KnowledgeStore

# SPEC-04 §3.1's project roles, validated where the refusal reaches the caller (AUDIT-074).
_PROJECT_ROLES = (PROJECT_ROLE_ADMIN, PROJECT_ROLE_MEMBER, PROJECT_ROLE_VIEWER)

_bearer = HTTPBearer(auto_error=False)

# R38: the ratified public ceilings, applied in the SCHEMA so an oversized request is refused by
# validation before a handler allocates anything. `PublicLimits` carries the deployment-tunable copy;
# these are the compile-time defaults the request models need, and they must not diverge — the test
# `test_schema_ceilings_match_the_configured_limits` pins them together.
_DEFAULT_LIMITS = PublicLimits()
JSON_BODY_MAX = _DEFAULT_LIMITS.json_body_bytes
ONTOLOGY_MAX = _DEFAULT_LIMITS.ontology_bytes
FREE_TEXT_MAX = _DEFAULT_LIMITS.free_text_bytes
ARRAY_MAX = _DEFAULT_LIMITS.public_array_items
PAGE_MAX = _DEFAULT_LIMITS.page_items
ADMIN_PAGE_MAX = _DEFAULT_LIMITS.admin_page_items
EXPORT_ROWS_MAX = _DEFAULT_LIMITS.audit_export_rows
WINDOW_DAYS_MAX = _DEFAULT_LIMITS.window_days
NAME_MAX = 512
SLUG_MAX = 128

router = APIRouter(prefix="/api/v1/admin", tags=["admin"])


class ProjectCreate(BaseModel):
    slug: str
    name: str


class TopicCreate(BaseModel):
    slug: str = Field(max_length=SLUG_MAX)
    name: str = Field(max_length=NAME_MAX)
    sensitivity: int = Field(default=0, ge=0, le=10)


class MembershipCreate(BaseModel):
    """AUDIT-074: attaching a user to the caller's project.

    The project is not a field — it comes from the token's scope (FR-12.3). The role is required
    rather than defaulted, because a membership created with a silently-chosen role is an authority
    decision nobody made.
    """

    user_id: str = Field(max_length=64)
    role: str = Field(max_length=32)
    can_curate: bool = False


class TopicGrant(BaseModel):
    """AUDIT-073: whose authority changes, stated explicitly.

    The user is named in the body rather than defaulting to the caller, because defaulting to the
    caller is exactly the hole this closes — `POST /topics` self-granted and nothing could grant to
    anyone else. The project is NOT a field: it comes from the token's scope, never from the client
    (FR-12.3).
    """

    user_id: str = Field(max_length=64)


class SourceCreate(BaseModel):
    name: str = Field(max_length=NAME_MAX)
    type: str = Field(default="folder", max_length=SLUG_MAX)
    policy: str = Field(default="llm", max_length=SLUG_MAX)
    default_tags: list[str] = Field(default_factory=list, max_length=ARRAY_MAX)
    review_if_sensitive: bool = True


class UserInvite(BaseModel):
    email: str = Field(max_length=NAME_MAX)
    role: str = Field(default="member", max_length=SLUG_MAX)


class PersonCreate(BaseModel):
    name: str = Field(max_length=NAME_MAX)
    topics: list[str] = Field(default_factory=list, max_length=ARRAY_MAX)
    channels: dict[str, str] = Field(default_factory=dict)
    quiet_hours: dict[str, str] = Field(default_factory=dict)
    language: str | None = Field(default=None, max_length=SLUG_MAX)


class PersonUpdate(BaseModel):
    topics: list[str] | None = Field(default=None, max_length=ARRAY_MAX)
    channels: dict[str, str] | None = None
    quiet_hours: dict[str, str] | None = None
    language: str | None = Field(default=None, max_length=SLUG_MAX)


class HuntAsk(BaseModel):
    question: str = Field(max_length=FREE_TEXT_MAX)
    topics: list[str] = Field(default_factory=list, max_length=ARRAY_MAX)


class SkillUpsert(BaseModel):
    # The full skill file: OKF frontmatter + body. Bounded like any other public body (R38).
    markdown: str = Field(max_length=JSON_BODY_MAX)


class ChunkApprove(BaseModel):
    # Curator-corrected tags for an ambiguous table (FR-1.5).
    tags: list[str] | None = Field(default=None, max_length=ARRAY_MAX)


class OntologyUpload(BaseModel):
    name: str = Field(max_length=NAME_MAX)
    format: str = Field(default="turtle", max_length=SLUG_MAX, description="owl|rdf|skos|turtle")
    content: str = Field(
        max_length=ONTOLOGY_MAX, description="The full OWL/RDF/SKOS document text."
    )
    uri_base: str | None = Field(default=None, max_length=NAME_MAX)


def _deps(request: Request) -> object:
    return request.app.state.deps


def _sm(request: Request) -> async_sessionmaker[AsyncSession]:
    sessionmaker: async_sessionmaker[AsyncSession] = _deps(request).sessionmaker  # type: ignore[attr-defined]
    return sessionmaker


async def _console_scope_for(
    sessionmaker: async_sessionmaker[AsyncSession], user_id: str, role: str, project_slug: str
) -> ProjectScope | None:
    """Scope a console-session user to a project they may act in (SPEC-14).

    ``role`` is the caller's PLATFORM role, and it is deliberately not consulted here: platform
    administration is not project content authority (AUDIT-020/R03), so every caller needs an
    explicit membership in this project — a project-admin of another project included (FR-12.5).
    The membership's own role and topics are what travel in the scope; a global role never widens
    them. ``None`` ⇒ denied ≡ absent (FR-4.3).
    """
    async with sessionmaker() as session:
        project_id = await session.scalar(
            select(models.Project.id).where(models.Project.slug == project_slug)
        )
        if project_id is None:
            return None
        membership = await session.scalar(
            select(models.ProjectMembership).where(
                models.ProjectMembership.user_id == uuid.UUID(user_id),
                models.ProjectMembership.project_id == project_id,
            )
        )
        if membership is None:
            return None
        return Principal(
            id=user_id,
            type=PrincipalType.HUMAN,
            allowed_topics=frozenset(membership.allowed_topics),
            can_curate=membership.can_curate,
            role=membership.role,
            platform_role=role,
        ).scope_for(str(project_id))


async def _identified_scope(
    request: Request, credentials: HTTPAuthorizationCredentials | None, project: str | None
) -> ProjectScope:
    """Resolve identity only — never authority — from either supported entry point.

    A project-scoped PAT/OAuth token carries its own project (FR-12.3); a console session must name
    the project it means with ``?project=<slug>`` and must be a member of it. Both produce the same
    :class:`ProjectScope`, so the capability decision that follows cannot depend on how the caller
    authenticated (the R04 defect: session and token were gated differently).
    """
    from rsc_brain.identity.resolve import resolve_scope
    from rsc_brain.identity.sessions import resolve_session

    sessionmaker = _sm(request)
    if credentials is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="missing bearer token")
    token = credentials.credentials
    scope = await resolve_scope(sessionmaker, token)
    if scope is not None:
        return scope
    user = await resolve_session(sessionmaker, token)
    if user is not None:
        scoped = (
            await _console_scope_for(sessionmaker, user.user_id, user.role, project)
            if project
            else None
        )
        if scoped is None:
            # No/unauthorized project → denied ≡ absent (never reveal another project exists).
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="not found")
        return scoped
    raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="invalid token")


def _requires(
    capability: Capability,
) -> Callable[..., Coroutine[Any, Any, ProjectScope]]:
    """A FastAPI dependency that resolves identity and decides ``capability`` before the route runs.

    Capabilities whose decision also depends on the *object* (a document's tags, a gap's topics)
    are decided a second time inside the route, once the object is known — the dependency is the
    floor, never the whole decision.
    """

    async def dependency(
        request: Request,
        credentials: HTTPAuthorizationCredentials | None = Depends(_bearer),
        project: str | None = None,
    ) -> ProjectScope:
        scope = await _identified_scope(request, credentials, project)
        enforce(decide(scope, capability))
        return scope

    return dependency


async def _needs_identity(
    request: Request,
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer),
    project: str | None = None,
) -> ProjectScope:
    """Resolve identity and decide nothing — for routes that act on ONE named object.

    Order matters for indistinguishability (FR-4.3): if the role were decided first, a caller of
    another project asking about this project's document would get the 403 shape while a caller
    asking about a genuinely nonexistent id got 404, which tells the first caller the document
    exists. So these routes look the object up in the caller's own project first (absent ⇒ 404) and
    only then decide the operation over its topics.
    """
    return await _identified_scope(request, credentials, project)


# One dependency singleton per capability the surface exposes, so every route names its
# operation and no route can silently reuse a different one.
_needs_manage_read = _requires(Capability.PROJECT_MANAGE_READ)
_needs_config_write = _requires(Capability.PROJECT_CONFIG_WRITE)
_needs_settings_write = _requires(Capability.PROJECT_SETTINGS_WRITE)
_needs_knowledge_read = _requires(Capability.KNOWLEDGE_READ)
_needs_review_decide = _requires(Capability.KNOWLEDGE_REVIEW_DECIDE)
_needs_usage_read = _requires(Capability.USAGE_READ)
_needs_hunt_manage = _requires(Capability.HUNT_MANAGE)
_needs_platform_project_create = _requires(Capability.PLATFORM_PROJECT_CREATE)
_needs_platform_user_invite = _requires(Capability.PLATFORM_USER_INVITE)
_needs_platform_credential_revoke = _requires(Capability.PLATFORM_CREDENTIAL_REVOKE)


def _identity(request: Request) -> IdentityService:
    return IdentityService(_deps(request).sessionmaker)  # type: ignore[attr-defined]


def _repo(request: Request) -> IngestRepository:
    return IngestRepository(_deps(request).sessionmaker)  # type: ignore[attr-defined]


# --- projects (global admin) ------------------------------------------------


@router.get("/projects")
async def list_projects(
    request: Request, scope: ProjectScope = Depends(_needs_manage_read)
) -> dict[str, object]:
    """The projects this caller may know about.

    R01 (strengthened during T001): this route returned every slug in the instance, so any caller
    that passed the old admin gate enumerated other tenants by name. Enumerating the whole instance
    is a platform operation; a project caller sees only the projects it is a member of.
    """
    identity = _identity(request)
    if isinstance(
        decide(scope, Capability.PLATFORM_PROJECT_LIST_ALL), Allow
    ):  # platform administration
        return {"projects": await identity.list_projects()}
    return {"projects": await identity.list_projects_for_user(scope.principal_id)}


@router.post("/projects", status_code=status.HTTP_201_CREATED)
async def create_project(
    body: ProjectCreate,
    request: Request,
    scope: ProjectScope = Depends(_needs_platform_project_create),
) -> dict[str, object]:
    project_id = await _identity(request).create_project(body.slug, body.name)
    return {"project_id": project_id, "slug": body.slug}


# --- users (global admin) ---------------------------------------------------


@router.post("/users/invite", status_code=status.HTTP_201_CREATED)
async def invite_user(
    body: UserInvite, request: Request, scope: ProjectScope = Depends(_needs_platform_user_invite)
) -> dict[str, object]:
    issued = await _identity(request).invite_user(body.email, role=body.role)
    # The invitation token is shown once (the console surfaces it to the inviter).
    return {"user_id": issued.id, "invitation_token": issued.token}


# --- project-scoped (project from the token) --------------------------------


@router.get("/topics")
async def list_topics(
    request: Request, scope: ProjectScope = Depends(_needs_manage_read)
) -> dict[str, object]:
    topics = await _repo(request).list_topics(scope)
    return {"topics": [{"slug": slug, "sensitivity": sens} for slug, sens in topics]}


@router.post("/topics", status_code=status.HTTP_201_CREATED)
async def create_topic(
    body: TopicCreate, request: Request, scope: ProjectScope = Depends(_needs_config_write)
) -> dict[str, object]:
    """Create a topic, and record the creator's authority over it explicitly.

    Topic authority is never implied by a role — not even the project administrator's (AUDIT-020;
    R01 holds that the highest project role still sees only the topics it holds). Without the grant,
    defining a topic would leave its own author unable to act on anything tagged with it, and the
    only way out would be a direct database write. So the grant is made here, on the membership,
    where it is visible and revocable.
    """
    identity = _identity(request)
    topic_id = await identity.create_topic(
        scope.project_id, body.slug, body.name, sensitivity=body.sensitivity
    )
    granted = await identity.grant_topics(scope.principal_id, scope.project_id, [body.slug])
    await audit_mod.record_audit(
        _sm(request),
        scope,
        action="topic:create",
        tool="console",
        topics_used=[body.slug],
    )
    return {"topic_id": topic_id, "slug": body.slug, "granted_topics": list(granted)}


def _membership_target(user_id: str) -> uuid.UUID:
    """The target principal's id, or a not-found refusal.

    AUDIT-078: every new route passed this straight into `uuid.UUID(...)` inside the service, so a
    malformed value raised `ValueError` and surfaced as a 500 with a traceback — a third response
    class alongside 201/404, emitted BEFORE the membership lookup and therefore distinguishable at
    zero cost. `api/authz.py` had already ratified the rule this now follows: "a malformed
    identifier is absent, not an error that confirms the route".
    """
    try:
        return uuid.UUID(user_id)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="not found") from exc


@router.get("/memberships")
async def list_memberships(
    request: Request, scope: ProjectScope = Depends(_needs_manage_read)
) -> dict[str, object]:
    """Who belongs to the caller's project, with the role and topic authority each holds.

    AUDIT-074: an administrator has to see this before granting anything — the topic grant refuses
    without a membership, and nothing reported whether one existed.
    """
    return {"memberships": await _identity(request).list_memberships(scope.project_id)}


@router.post("/memberships", status_code=status.HTTP_201_CREATED)
async def create_membership(
    body: MembershipCreate,
    request: Request,
    scope: ProjectScope = Depends(_needs_config_write),
) -> dict[str, object]:
    """Attach a user to the caller's project (AUDIT-074).

    `add_membership` previously had one caller, the first owner's bootstrap, so every later user
    belonged to no project and could be given nothing. No topic is granted here: authority stays a
    separate explicit act, because empty authority is never all topics (AUDIT-020, R01).
    """
    identity = _identity(request)
    _membership_target(body.user_id)
    if body.role not in _PROJECT_ROLES:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"unknown role; expected one of {', '.join(_PROJECT_ROLES)}",
        )
    if await identity.membership_topics(body.user_id, scope.project_id) is not None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="a membership is unique per user and project",
        )
    try:
        membership_id = await identity.add_membership(
            body.user_id, scope.project_id, role=body.role, can_curate=body.can_curate
        )
    except IntegrityError as exc:
        # AUDIT-078: the pre-check above and this write are separate transactions, so two concurrent
        # creates both pass it and the loser meets the unique constraint — which is the real arbiter
        # and holds. It used to surface as a 500, i.e. the same request answered 409 a second earlier.
        # A violated user foreign key lands here too, and answers as absent rather than confirming
        # from a 500-vs-201 split whether a given id exists somewhere on the instance.
        if "project_memberships" in str(exc.orig):
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="a membership is unique per user and project",
            ) from exc
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="not found") from exc
    await audit_mod.record_audit(
        _sm(request),
        scope,
        # AUDIT-078: the trail used to say an authority change happened and never for WHOM, which is
        # the one question a permission audit exists to answer. No target column exists, so the
        # target rides in the action until one does.
        action=f"membership:create user_id={body.user_id} role={body.role}",
        tool="console",
        topics_used=[],
    )
    return {"membership_id": membership_id, "user_id": body.user_id, "role": body.role}


@router.delete("/memberships/{user_id}")
async def delete_membership(
    user_id: str, request: Request, scope: ProjectScope = Depends(_needs_config_write)
) -> dict[str, object]:
    """Detach a user from the caller's project; their access tokens stop resolving with it."""
    _membership_target(user_id)
    if not await _identity(request).remove_membership(user_id, scope.project_id):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="not found")
    await audit_mod.record_audit(
        _sm(request),
        scope,
        action=f"membership:remove user_id={user_id}",
        tool="console",
        topics_used=[],
    )
    return {"removed": user_id}


async def _change_authority(
    request: Request,
    scope: ProjectScope,
    slug: str,
    user_id: str,
    *,
    action: str,
) -> dict[str, object]:
    """Grant or revoke one topic on another principal's membership (AUDIT-073).

    SPEC-04 §3.1 requires topic authority to be "persistidos y expuestos por API"; only the
    self-grant inside `create_topic` was. The project comes from the caller's scope, so an
    administrator of one project can never reach into another (FR-12.3), and a slug outside this
    project's taxonomy is refused by the service (§3.2).
    """
    identity = _identity(request)
    _membership_target(user_id)
    if action == "grant":
        # AUDIT-078: this route was gated by `_needs_config_write` alone, which calls `decide` with
        # no `object_topics` — and `_topics_authorized(scope, None)` returns True. So a project-admin
        # holding only `general` could POST /topics/payroll/grants for their OWN user id and read
        # every sensitivity-4 chunk on the next request. `project-admin` implied all topics, which is
        # exactly what R01/AUDIT-020 and docs/reference/permissions.md say it must never do — cited,
        # verbatim, in this module's own docstrings.
        #
        # Subset semantics, the rule five other mutations already follow: you may only hand over
        # authority you hold. Self-granting a held topic stays a no-op; self-granting an unheld one
        # is now refused, so no separate self-target rule is needed.
        #
        # Revoking deliberately does NOT require it: escalation needs authority, de-escalation does
        # not, and requiring it would strand a topic nobody present can withdraw.
        enforce(decide(scope, Capability.PROJECT_CONFIG_WRITE, object_topics=[slug]))
    current = await identity.membership_topics(user_id, scope.project_id)
    if current is None:
        # Denied ≡ absent: an administrator of this project learns nothing about memberships
        # elsewhere, and nothing about whether that user exists at all (FR-4.3).
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="not found")
    try:
        if action == "grant":
            topics = await identity.grant_topics(user_id, scope.project_id, [slug])
        else:
            topics = await identity.revoke_topics(user_id, scope.project_id, [slug])
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc
    await audit_mod.record_audit(
        _sm(request),
        scope,
        # AUDIT-078: the topic was recorded and the recipient was not.
        action=f"topic:{action} user_id={user_id}",
        tool="console",
        topics_used=[slug],
    )
    return {"slug": slug, "user_id": user_id, "allowed_topics": list(topics)}


@router.post("/topics/{slug}/grants", status_code=status.HTTP_201_CREATED)
async def grant_topic(
    slug: str,
    body: TopicGrant,
    request: Request,
    scope: ProjectScope = Depends(_needs_config_write),
) -> dict[str, object]:
    """Grant a topic to a principal's membership in the caller's project."""
    return await _change_authority(request, scope, slug, body.user_id, action="grant")


@router.delete("/topics/{slug}/grants/{user_id}")
async def revoke_topic(
    slug: str,
    user_id: str,
    request: Request,
    scope: ProjectScope = Depends(_needs_config_write),
) -> dict[str, object]:
    """Withdraw a topic from a principal's membership in the caller's project."""
    return await _change_authority(request, scope, slug, user_id, action="revoke")


@router.get("/sources")
async def list_sources(
    request: Request, scope: ProjectScope = Depends(_needs_manage_read)
) -> dict[str, object]:
    sources = await _repo(request).list_sources(scope)
    return {
        "sources": [
            {
                "id": s.id,
                "name": s.name,
                "type": s.type,
                "policy": s.policy,
                "default_tags": list(s.default_tags),
                "review_if_sensitive": s.review_if_sensitive,
            }
            for s in sources
        ]
    }


@router.post("/sources", status_code=status.HTTP_201_CREATED)
async def create_source(
    body: SourceCreate, request: Request, scope: ProjectScope = Depends(_needs_config_write)
) -> dict[str, object]:
    source_id = await SourceService(_repo(request)).create(
        scope,
        name=body.name,
        type_=body.type,
        policy=body.policy,
        default_tags=body.default_tags,
        review_if_sensitive=body.review_if_sensitive,
    )
    return {"source_id": source_id, "name": body.name}


@router.get("/documents/pending")
async def list_pending_documents(
    request: Request, scope: ProjectScope = Depends(_needs_manage_read)
) -> dict[str, object]:
    pending = await _repo(request).list_documents_by_status(scope, "pending_approval")
    return {
        "documents": [
            {"document_id": d.id, "title": d.title, "proposed_tags": list(d.doc_tags)}
            for d in pending
        ]
    }


@router.get("/gaps")
async def list_project_gaps(
    request: Request,
    scope: ProjectScope = Depends(_needs_manage_read),
    audience: str | None = None,
) -> dict[str, object]:
    """Project gaps. ``audience=agent`` returns the separate agent-gap view (FR-14.6); ``human``
    the human-driven gaps eligible for the trigger; omitted returns all."""
    gaps = await list_gaps(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope,
        audience=audience if audience in {"human", "agent"} else None,
    )
    return {"gaps": gaps}


def _knowledge_store(request: Request) -> KnowledgeStore:
    return KnowledgeStore(_deps(request).sessionmaker)  # type: ignore[attr-defined]


@router.get("/corrections")
async def list_corrections(
    request: Request,
    scope: ProjectScope = Depends(_needs_knowledge_read),
    status_filter: str | None = None,
    target_claim: str | None = None,
    author: str | None = None,
) -> dict[str, object]:
    """Corrections feed (SPEC-19, FR-15.12): feed / by-claim / by-person; the ``pending_confirmation``
    queue is ``status_filter=pending_confirmation``."""
    rows = await _knowledge_store(request).list_corrections(
        scope, status=status_filter, target_claim=target_claim, author=author
    )
    return {"corrections": rows}


@router.get("/corrections/metrics")
async def correction_metrics(
    request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    """The Learning-Layer §7 metrics (SPEC-19, FR-15.12/§3.3)."""
    return await _knowledge_store(request).correction_metrics(scope)


@router.post("/corrections/{correction_id}/revert")
async def revert_correction(
    correction_id: str, request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    """Revert a correction (FR-15.8).

    The one mutation whose matrix row is not a pure role: the project administrator OR the owner of
    the target claim's topics may revert. That is expressed as
    :attr:`Capability.CORRECTION_REVERT` with the ownership fact passed in — the bespoke
    ``is_admin or is_owner`` gate this replaces was the reason T001 could not fold this route into
    the uniform matrix. A refusal is still audited.
    """
    from rsc_brain.knowledge.corrections import CorrectionService
    from rsc_brain.stores.age_graph_store import AgeGraphStore

    deps = _deps(request)
    sessionmaker = _sm(request)
    store = KnowledgeStore(sessionmaker)
    correction = await store.get_correction(scope, correction_id)
    if correction is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="correction not found")
    target = await store.get_claim(scope, str(correction.target_claim))
    if target is None:
        # The correction exists but its target claim is outside the caller's topic visibility:
        # reverting it would mutate knowledge the caller cannot see, and saying so would confirm
        # the claim exists. Absent and hidden look identical (FR-4.3, R06).
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="correction not found")
    tags = list(target.tags)
    is_owner = await store.person_owns_any_tag(scope, scope.principal_id, tags)
    decision = decide(
        scope, Capability.CORRECTION_REVERT, object_topics=tags, object_owner=is_owner
    )
    if not isinstance(decision, Allow):
        await audit_mod.record_audit(
            sessionmaker,
            scope,
            action="correct_knowledge:revert_denied",
            tool="console",
            denied=True,
        )
        enforce(decision)
    service = CorrectionService(
        store=store,
        graph=AgeGraphStore(sessionmaker),
        gateway=deps.gateway,  # type: ignore[attr-defined]
    )
    outcome = await service.revert(scope, correction_id)
    await audit_mod.record_audit(
        sessionmaker, scope, action=f"correct_knowledge:{outcome.status}", tool="console"
    )
    return {"status": outcome.status, "explanation": outcome.explanation}


@router.get("/claims/disputed")
async def list_disputed_claims(
    request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    """Claims currently flagged disputed (SPEC-19, FR-13.5)."""
    rows = await _knowledge_store(request).list_disputed_claims(scope)
    return {"claims": rows}


@router.get("/contradictions/resolutions")
async def list_contradiction_resolutions(
    request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    """Resolved contradictions — who won, by what score (SPEC-19, FR-13.5/FR-5.3)."""
    rows = await _knowledge_store(request).list_contradiction_resolutions(scope)
    return {"resolutions": rows}


def _skill_store(request: Request) -> object:
    from rsc_brain.skills.store import SkillStore

    return SkillStore(_deps(request).sessionmaker)  # type: ignore[attr-defined]


@router.get("/skills")
async def list_skills_admin(
    request: Request, scope: ProjectScope = Depends(_needs_knowledge_read), state: str | None = None
) -> dict[str, object]:
    """List a project's skills (SPEC-20, FR-7.1). Read — console-consumable."""
    rows = await _skill_store(request).list_all(scope, state=state)  # type: ignore[attr-defined]
    return {
        "skills": [
            {
                "slug": s.slug,
                "title": s.title,
                "state": s.state,
                "stale": s.stale,
                "tags": list(s.tags),
            }
            for s in rows
        ]
    }


@router.post("/skills", status_code=status.HTTP_201_CREATED)
async def create_skill_admin(
    body: SkillUpsert, request: Request, scope: ProjectScope = Depends(_needs_config_write)
) -> dict[str, object]:
    """Create a skill from its markdown (OKF frontmatter + body)."""
    from rsc_brain.skills.frontmatter import SkillFrontmatterError, parse_skill

    try:
        frontmatter, skill_body = parse_skill(body.markdown)
    except SkillFrontmatterError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT, detail=str(exc)
        ) from exc
    skill_id = await _skill_store(request).create(scope, frontmatter, skill_body)  # type: ignore[attr-defined]
    return {"skill_id": skill_id, "slug": frontmatter.slug}


@router.post("/skills/{slug}/archive")
async def archive_skill_admin(
    slug: str, request: Request, scope: ProjectScope = Depends(_needs_config_write)
) -> dict[str, object]:
    await _skill_store(request).set_state(scope, slug, "archived")  # type: ignore[attr-defined]
    return {"slug": slug, "archived": True}


@router.get("/review-queue")
async def review_queue(
    request: Request,
    scope: ProjectScope = Depends(_needs_knowledge_read),
    source: str | None = None,
) -> dict[str, object]:
    """The unified needs_review queue (SPEC-21, FR-13.6): all four sources, filterable by source."""
    from rsc_brain.review.queue import list_review_queue

    items = await list_review_queue(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope,
        source=source,
    )
    counts: dict[str, int] = {}
    for item in items:
        counts[item.source] = counts.get(item.source, 0) + 1
    return {
        "items": [
            {
                "source": i.source,
                "id": i.id,
                "preview": i.preview,
                "detail": i.detail,
                # R08: held chunks, agent submissions and guardrail catches are untrusted text shown
                # for a decision; the marker travels with them (FR-14.8).
                "content_type": UNTRUSTED,
            }
            for i in items
        ],
        "counts": counts,
    }


@router.post("/review-queue/chunks/{chunk_id}/resolve")
async def resolve_chunk_item(
    chunk_id: str,
    body: ChunkApprove,
    request: Request,
    approve: bool,
    scope: ProjectScope = Depends(_needs_identity),
) -> dict[str, object]:
    """Approve (embed + curator tags + recallable) or reject a needs_review chunk (FR-1.5/4.4/14.4).

    Curation is the one capability ``can_curate`` grants, and only inside its own topics: the
    decision covers the chunk's current topics AND any curator-corrected tags, so a review decision
    can never move content into a topic the curator does not hold.
    """
    from rsc_brain.review.resolve import resolve_chunk

    deps = _deps(request)
    chunk_topics = await object_topics(
        _sm(request), scope, models.Chunk, models.Chunk.id, chunk_id, topics_attr="tags"
    )
    if chunk_topics is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="not found")
    decide_object(
        scope,
        Capability.KNOWLEDGE_REVIEW_DECIDE,
        [*chunk_topics, *(body.tags or [])],
    )
    outcome = await resolve_chunk(
        deps.sessionmaker,  # type: ignore[attr-defined]
        scope,
        chunk_id,
        approve=approve,
        gateway=deps.gateway,  # type: ignore[attr-defined]
        tags=body.tags,
    )
    await audit_mod.record_audit(
        deps.sessionmaker,  # type: ignore[attr-defined]
        scope,
        action=f"review:chunk:{outcome}",
        tool="console",
    )
    return {"chunk_id": chunk_id, "outcome": outcome}


@router.post("/review-queue/merges/{proposal_id}/resolve")
async def resolve_merge_item(
    proposal_id: str,
    request: Request,
    approve: bool,
    scope: ProjectScope = Depends(_needs_identity),
) -> dict[str, object]:
    """Approve (apply the merge) or reject an entity-merge proposal (FR-1.9)."""
    from rsc_brain.review.resolve import resolve_merge

    merge_topics = await merge_proposal_topics(_sm(request), scope, proposal_id)
    if merge_topics is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="not found")
    decide_object(scope, Capability.KNOWLEDGE_REVIEW_DECIDE, merge_topics)
    outcome = await resolve_merge(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope,
        proposal_id,
        approve=approve,
        resolved_by=scope.principal_id,
    )
    await audit_mod.record_audit(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope,
        action=f"review:merge:{outcome}",
        tool="console",
    )
    return {"proposal_id": proposal_id, "outcome": outcome}


@router.get("/metrics/product")
async def product_metrics_endpoint(
    request: Request,
    scope: ProjectScope = Depends(_needs_knowledge_read),
    window_days: int = Query(default=30, ge=1, le=WINDOW_DAYS_MAX),
) -> dict[str, object]:
    """The four PRD §8 metric families for a project (SPEC-23) — adoption, quality, knowledge,
    health. Project-scoped in-query (FR-12.5); the console consumes this."""
    from rsc_brain.observability.product import product_metrics

    return await product_metrics(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope,
        window_days=window_days,
    )


@router.get("/timeline")
async def project_timeline(
    request: Request,
    scope: ProjectScope = Depends(_needs_knowledge_read),
    topic: str | None = None,
    entity: str | None = None,
    as_of: str | None = None,
) -> dict[str, object]:
    """Contract parity for the MCP `timeline` tool (SPEC-17, FR-16.6): the ordered evolution of a
    topic/entity, permission + project scoped (FR-4.3/12.5). For the console lane (SPEC-19)."""
    from rsc_brain.mcp.tools import do_timeline

    output = await do_timeline(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope,
        topic=topic,
        entity=entity,
        as_of=as_of,
    )
    return {"timeline": output.model_dump()}


@router.get("/audit")
async def list_audit(
    request: Request,
    scope: ProjectScope = Depends(_needs_manage_read),
    action: str | None = None,
    tool: str | None = None,
    principal_type: str | None = None,
    principal_id: str | None = None,
    denied: bool | None = None,
    since: str | None = None,
    until: str | None = None,
    limit: int = Query(default=100, ge=1, le=ADMIN_PAGE_MAX),
) -> dict[str, object]:
    """Filterable audit log (SPEC-26 FR-13.7). Project-scoped in-query (a project-admin sees only
    their project); `query_text` is NULL when `query_text_logging` is OFF (FR-13.9)."""
    rows = await audit_mod.query_audit(
        _sm(request),
        scope,
        action=action,
        tool=tool,
        principal_type=principal_type,
        principal_id=principal_id,
        denied=denied,
        since=since,
        until=until,
        limit=limit,
    )
    return {"audit": rows}


@router.get("/audit/export", response_class=Response)
async def export_audit(
    request: Request,
    scope: ProjectScope = Depends(_needs_manage_read),
    action: str | None = None,
    tool: str | None = None,
    principal_type: str | None = None,
    principal_id: str | None = None,
    denied: bool | None = None,
    since: str | None = None,
    until: str | None = None,
    limit: int = Query(default=EXPORT_ROWS_MAX, ge=1, le=EXPORT_ROWS_MAX),
) -> Response:
    """CSV export of the filtered audit log (SPEC-26 FR-13.7, parity with `brain audit --export`).
    The export itself is audited (FR-4.5)."""
    sessionmaker = _deps(request).sessionmaker  # type: ignore[attr-defined]
    rows = await audit_mod.query_audit(
        sessionmaker,
        scope,
        action=action,
        tool=tool,
        principal_type=principal_type,
        principal_id=principal_id,
        denied=denied,
        since=since,
        until=until,
        limit=limit,
    )
    await audit_mod.record_audit(sessionmaker, scope, action="audit_export", tool="console")
    return Response(
        content=audit_mod.to_csv(rows),
        media_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="audit.csv"'},
    )


@router.get("/usage")
async def usage_endpoint(
    request: Request,
    scope: ProjectScope = Depends(_needs_usage_read),
    days: int = Query(default=7, ge=1, le=WINDOW_DAYS_MAX),
) -> dict[str, object]:
    """This project's per-capability/day token + call usage (SPEC-26 FR-13.7, AUDIT-021 R12).

    Same source as ``brain usage``, so the console figures always match the CLI. The counters used to
    be instance-global: every project read the same pooled total, which reconciled with nobody.
    """
    from rsc_brain.gateway.usage import usage_by_day

    rows = await usage_by_day(_sm(request), days=days, project_id=scope.project_id)
    return {"usage": rows}


@router.get("/graph/entity")
async def entity_graph_endpoint(
    request: Request,
    scope: ProjectScope = Depends(_needs_knowledge_read),
    name: str = Query(default="", max_length=NAME_MAX),
    limit: int = Query(default=25, ge=1, le=ADMIN_PAGE_MAX),
    offset: int = Query(default=0, ge=0),
) -> dict[str, object]:
    """A bounded, paginated neighborhood of one entity (SPEC-26 FR-13.8). Permission-scoped: an
    entity with no visible claims is indistinguishable from a non-existent one (404, FR-4.3)."""
    from rsc_brain.knowledge.entity_graph import entity_neighborhood
    from rsc_brain.stores.age_graph_store import AgeGraphStore

    sessionmaker = _deps(request).sessionmaker  # type: ignore[attr-defined]
    view = await entity_neighborhood(
        sessionmaker, AgeGraphStore(sessionmaker), scope, name=name, limit=limit, offset=offset
    )
    if view is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="entity not found")
    return {
        "center": {
            "id": view.center.id,
            "name": view.center.name,
            "type": view.center.type,
            "anchored": view.center.anchored,
        },
        "neighbors": [
            {"id": n.id, "name": n.name, "type": n.type, "anchored": n.anchored}
            for n in view.neighbors
        ],
        "edges": [{"source": e.source, "target": e.target, "type": e.type} for e in view.edges],
        "total": view.total,
        "offset": view.offset,
        "limit": view.limit,
    }


@router.delete("/connections/{connection_id}")
async def admin_revoke_connection(
    connection_id: str,
    request: Request,
    scope: ProjectScope = Depends(_needs_platform_credential_revoke),
) -> dict[str, object]:
    """Admin revokes any user's OAuth connection (FR-4.13 admin part). Stops resolving <5s."""
    from rsc_brain.identity import sessions

    await sessions.revoke_connection(_deps(request).sessionmaker, connection_id)  # type: ignore[attr-defined]
    return {"ok": True, "revoked": connection_id}


# --- read observability (SPEC-14, all scoped to the token's project — FR-12.5) ---------------


class QueryTextLogging(BaseModel):
    enabled: bool


@router.get("/observability/activity")
async def observability_activity(
    request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    """Activity dashboard aggregates (FR-13.2): recalls/day, active principals, p95, denied."""
    return await audit_mod.activity_summary(_sm(request), scope)


@router.get("/observability/recalls")
async def observability_recalls(
    request: Request,
    scope: ProjectScope = Depends(_needs_knowledge_read),
    principal_type: str | None = None,
    denied: bool | None = None,
    limit: int = Query(default=100, ge=1, le=ADMIN_PAGE_MAX),
) -> dict[str, object]:
    """Live recall stream (FR-13.3/14.3): filter by principal + denial; query_text present only
    when the project's logging is ON."""
    return {
        "recalls": await audit_mod.recall_stream(
            _sm(request),
            scope,
            principal_type=principal_type,
            denied=denied,
            limit=limit,
        )
    }


@router.get("/observability/health")
async def observability_health(
    request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    """Service health (FR-13.2): the pending-approval queue depth + extraction error count."""
    sm = _deps(request).sessionmaker  # type: ignore[attr-defined]
    pid = uuid.UUID(scope.project_id)
    async with sm() as session:
        pending = await session.scalar(
            select(func.count())
            .select_from(models.Document)
            .where(models.Document.project_id == pid, models.Document.status == "pending_approval")
        )
        errors = await session.scalar(
            select(func.count())
            .select_from(models.IngestError)
            .where(models.IngestError.project_id == pid)
        )
    return {
        "database": "ok",
        "pending_approval": int(pending or 0),
        "ingest_errors": int(errors or 0),
    }


@router.get("/settings/query-text-logging")
async def get_query_text_logging(
    request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    enabled = await audit_mod.query_text_logging_enabled(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope.project_id,
    )
    return {"enabled": enabled}


@router.put("/settings/query-text-logging")
async def put_query_text_logging(
    body: QueryTextLogging, request: Request, scope: ProjectScope = Depends(_needs_settings_write)
) -> dict[str, object]:
    """Toggle FR-13.9 for the project. OFF ⇒ the query text stops being persisted (server-side)."""
    await audit_mod.set_query_text_logging(
        _deps(request).sessionmaker,  # type: ignore[attr-defined]
        scope.project_id,
        enabled=body.enabled,
    )
    return {"enabled": body.enabled}


# --- ingest observability + D13 approval queue (FR-13.4), console-session callable --------------


class ApproveDoc(BaseModel):
    # Corrected proposed tags (FR-1.15 inheritance on approve).
    tags: list[str] | None = Field(default=None, max_length=ARRAY_MAX)


class RejectDoc(BaseModel):
    reason: str = Field(max_length=FREE_TEXT_MAX)


@router.get("/observability/ingest")
async def observability_ingest(
    request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    """Ingest runs per document (stage checkpoints) + extraction errors with their chunk (FR-13.4)."""
    repo = IngestRepository(_deps(request).sessionmaker)  # type: ignore[attr-defined]
    runs = await repo.list_run_statuses(scope)
    async with _deps(request).sessionmaker() as session:  # type: ignore[attr-defined]
        error_rows = await session.execute(
            select(
                models.IngestError.document_id,
                models.IngestError.chunk_ref,
                models.IngestError.stage,
                models.IngestError.error,
            )
            .where(models.IngestError.project_id == uuid.UUID(scope.project_id))
            .order_by(models.IngestError.created_at.desc())
            .limit(200)
        )
        errors = [
            {"document_id": str(doc) if doc else None, "chunk": chunk, "stage": stage, "error": err}
            for doc, chunk, stage, err in error_rows.all()
        ]
    return {
        "runs": [
            {
                "document_id": r.document_id,
                "phase": r.phase,
                "completed_stages": list(r.completed_stages),
                "chunks_created": r.chunks_created,
                "claims_generated": r.claims_generated,
                "discarded_chunks": r.discarded_chunks,
                "error": r.error,
            }
            for r in runs
        ],
        "errors": errors,
    }


@router.get("/documents/pending/preview")
async def pending_document_previews(
    request: Request, scope: ProjectScope = Depends(_needs_manage_read)
) -> dict[str, object]:
    """The D13 queue with a text preview + proposed (editable) tags + source, for the console."""
    repo = IngestRepository(_deps(request).sessionmaker)  # type: ignore[attr-defined]
    pending = await repo.list_documents_by_status(scope, "pending_approval")
    out: list[dict[str, object]] = []
    async with _deps(request).sessionmaker() as session:  # type: ignore[attr-defined]
        for doc in pending:
            preview = await session.scalar(
                select(models.Chunk.text)
                .where(
                    models.Chunk.document_id == uuid.UUID(doc.id),
                    models.Chunk.project_id == uuid.UUID(scope.project_id),
                )
                .order_by(models.Chunk.id)
                .limit(1)
            )
            out.append(
                {
                    "document_id": doc.id,
                    "title": doc.title,
                    "proposed_tags": list(doc.doc_tags),
                    "source_id": doc.source_id,
                    "preview": (preview or "")[:280],
                    # R08: this is the least vetted text in the product — a document nobody has
                    # approved — rendered into an operator's browser. It carries the same marker a
                    # recall fragment does, so no consumer of this API can mistake it for trusted
                    # content (FR-14.8).
                    "content_type": UNTRUSTED,
                }
            )
    return {"documents": out}


@router.post("/documents/{document_id}/approve")
async def approve_document(
    document_id: str,
    body: ApproveDoc,
    request: Request,
    scope: ProjectScope = Depends(_needs_identity),
) -> dict[str, object]:
    """Approve a pending doc from the console (D13); corrected tags inherit to chunks (FR-1.15).

    R02: approving publishes every topic the document carries, and a corrected tag moves it into a
    new one, so the decision covers the union of the document's tags and the applied ones — a caller cannot publish into, or out of,
    a topic it does not hold. A document in another project is absent, never denied (FR-4.3).
    """
    from rsc_brain.ingest.pipeline import DocumentNotFoundError

    await decide_document(_sm(request), scope, document_id, extra_tags=body.tags)
    service, _ = _deps(request).service()  # type: ignore[attr-defined]
    try:
        run = await service.approve(scope, document_id, tags=body.tags, approver=scope.principal_id)
    except DocumentNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="not found") from exc
    return {"document_id": document_id, "phase": run.phase}


@router.post("/documents/{document_id}/reject")
async def reject_document(
    document_id: str,
    body: RejectDoc,
    request: Request,
    scope: ProjectScope = Depends(_needs_identity),
) -> dict[str, object]:
    """Reject a pending doc from the console (D13): nothing reaches the graph.

    R02: rejecting is a lifecycle decision like approving — it terminates a document other people's
    topics may depend on — so it needs the same document-lifecycle capability and topic scope.
    """
    from rsc_brain.ingest.pipeline import DocumentNotFoundError

    await decide_document(_sm(request), scope, document_id)
    service, _ = _deps(request).service()  # type: ignore[attr-defined]
    try:
        run = await service.reject(scope, document_id, reason=body.reason)
    except DocumentNotFoundError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="not found") from exc
    return {"document_id": document_id, "phase": run.phase}


# --- hunting: persons, hunts, gap promotion (SPEC-15, FR-6.1/6.2/6.6) -----------------------


def _directory(request: Request) -> object:
    from rsc_brain.hunting.directory import PersonDirectory

    return PersonDirectory(_deps(request).sessionmaker)  # type: ignore[attr-defined]


def _hunts(request: Request) -> object:
    """The ONE hunt service the app was configured with (R28).

    This used to build ``HuntService(sessionmaker)`` right here: no channel, so every hunt went to the
    recorder that sends nothing, and no base URL, so every reply link pointed at a host that does not
    exist. The configured service is assembled once in ``create_app`` and reused.
    """
    return request.app.state.hunts


@router.get("/persons")
async def list_persons(
    request: Request, scope: ProjectScope = Depends(_needs_manage_read)
) -> dict[str, object]:
    rows = await _directory(request).list(scope)  # type: ignore[attr-defined]
    return {
        "persons": [
            {
                "id": p.id,
                "name": p.name,
                "topics": list(p.topics),
                "channels": p.channels,
                "quiet_hours": p.quiet_hours,
                "language": p.language,
            }
            for p in rows
        ]
    }


@router.post("/persons", status_code=status.HTTP_201_CREATED)
async def create_person(
    body: PersonCreate, request: Request, scope: ProjectScope = Depends(_needs_config_write)
) -> dict[str, object]:
    person_id = await _directory(request).add(  # type: ignore[attr-defined]
        scope,
        name=body.name,
        channels=body.channels,
        topics=body.topics,
        quiet_hours=body.quiet_hours,
        language=body.language,
    )
    return {"person_id": person_id, "name": body.name}


@router.patch("/persons/{person_id}")
async def update_person(
    person_id: str,
    body: PersonUpdate,
    request: Request,
    scope: ProjectScope = Depends(_needs_config_write),
) -> dict[str, object]:
    await _directory(request).update(  # type: ignore[attr-defined]
        scope,
        person_id,
        topics=body.topics,
        channels=body.channels,
        quiet_hours=body.quiet_hours,
        language=body.language,
    )
    return {"person_id": person_id, "updated": True}


@router.delete("/persons/{person_id}")
async def delete_person(
    person_id: str, request: Request, scope: ProjectScope = Depends(_needs_config_write)
) -> dict[str, object]:
    await _directory(request).remove(scope, person_id)  # type: ignore[attr-defined]
    return {"person_id": person_id, "removed": True}


@router.get("/hunts")
async def list_hunts(
    request: Request,
    scope: ProjectScope = Depends(_needs_knowledge_read),
    open_only: bool = False,
) -> dict[str, object]:
    hunts = await _hunts(request).list_hunts(scope, open_only=open_only)  # type: ignore[attr-defined]
    return {"hunts": hunts}


@router.get("/hunts/{hunt_id}")
async def get_hunt(
    hunt_id: str, request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    hunt = await _hunts(request).get_hunt(scope, hunt_id)  # type: ignore[attr-defined]
    if hunt is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="hunt not found")
    return {"hunt": hunt}


@router.post("/hunts/ask", status_code=status.HTTP_201_CREATED)
async def ask_hunt(
    body: HuntAsk, request: Request, scope: ProjectScope = Depends(_needs_hunt_manage)
) -> dict[str, object]:
    """Open a MANUAL hunt (FR-6.2c) routed by topic overlap (NO_OWNER if unowned).

    The question is routed to whoever owns the topics it names, so the caller must hold them.
    """
    decide_object(scope, Capability.HUNT_MANAGE, body.topics)
    outcome = await _hunts(request).create_manual(  # type: ignore[attr-defined]
        scope, question=body.question, topics=body.topics
    )
    return {
        "hunt_id": outcome.hunt_id,
        "state": str(outcome.state),
        "person_id": outcome.person_id,
        "throttled": outcome.throttled,
        # R28: an operator has to be able to tell "asked" from "recorded but never sent".
        "delivered": outcome.delivered,
    }


@router.post("/gaps/{gap_id}/promote", status_code=status.HTTP_201_CREATED)
async def promote_gap(
    gap_id: str, request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    """Promote an agent gap to a hunt (FR-14.6 — agent gaps never trigger automatically).

    Promoting sends the gap's question to a human owner, so it needs the gap-promotion capability
    over the gap's own topics; a gap in another project is absent (FR-4.3).
    """
    gap_topics = await object_topics(
        _sm(request), scope, models.Gap, models.Gap.id, gap_id, topics_attr="topics"
    )
    if gap_topics is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="gap not found")
    decide_object(scope, Capability.GAP_PROMOTE, gap_topics)
    outcome = await _hunts(request).promote_agent_gap(scope, gap_id)  # type: ignore[attr-defined]
    if outcome is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="gap not found")
    return {"hunt_id": outcome.hunt_id, "state": str(outcome.state)}


# --- ontology (SPEC-24, FR-17.1/17.7 — optional, off by default) -------------


def _ontology_store(request: Request) -> object:
    from rsc_brain.ontology.store import OntologyStore

    return OntologyStore(_deps(request).sessionmaker)  # type: ignore[attr-defined]


@router.get("/ontologies")
async def list_ontologies(
    request: Request, scope: ProjectScope = Depends(_needs_knowledge_read)
) -> dict[str, object]:
    """List a project's ontologies (SPEC-24, FR-17.1). Read — console-consumable."""
    rows = await _ontology_store(request).list_all(scope)  # type: ignore[attr-defined]
    return {
        "ontologies": [
            {
                "id": o.id,
                "name": o.name,
                "format": o.format,
                "version": o.version,
                "active": o.active,
                "triples": o.triples,
            }
            for o in rows
        ]
    }


@router.post("/ontologies", status_code=status.HTTP_201_CREATED)
async def add_ontology(
    body: OntologyUpload, request: Request, scope: ProjectScope = Depends(_needs_config_write)
) -> dict[str, object]:
    """Validate and store a versioned ontology (SPEC-24, FR-17.1). Invalid RDF → 422."""
    from rsc_brain.ontology.index import OntologyParseError

    try:
        ontology_id = await _ontology_store(request).add(  # type: ignore[attr-defined]
            scope,
            name=body.name,
            content=body.content,
            fmt=body.format,
            uri_base=body.uri_base,
        )
    except OntologyParseError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT, detail=f"invalid ontology: {exc}"
        ) from exc
    return {"ontology_id": ontology_id, "name": body.name}


@router.get("/ontologies/coverage")
async def ontology_coverage(
    request: Request,
    scope: ProjectScope = Depends(_needs_knowledge_read),
    top: int = Query(default=10, ge=1, le=PAGE_MAX),
) -> dict[str, object]:
    """Anchoring coverage: % anchored + top unanchored names (SPEC-24, FR-17.7)."""
    coverage: dict[str, object] = await _ontology_store(request).coverage(  # type: ignore[attr-defined]
        scope, top_n=top
    )
    return coverage
